version: '3.1'
services:
  mysql:
    container_name: contact-list-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: contact-list
      MYSQL_USER: contact-list
      MYSQL_PASSWORD: 123456
  node:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: contact-list-node
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app/:/usr/local/nodejs/contact-list
      - /usr/local/nodejs/contact-list/node_modules
    command: ["./wait-for-it.sh", "mysql:3306", "--", "nodemon", "/bin/www"]
  nginx:
    container_name: contact-list-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./front/dist/front:/usr/share/nginx/html/contact-list
    ports:
      - 8083:80