version: '3.1'
services:
  mysql:
    container_name: contact-list-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: contact-list
      MYSQL_USER: contact-list
      MYSQL_PASSWORD: 123456
  node:
    depends_on:
      - mysql
    build:
      context: ./app
      dockerfile: ../docker/node/Dockerfile
    container_name: contact-list-node
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app/:/usr/local/nodejs/contact-list
      - /usr/local/nodejs/contact-list/node_modules
    command: ["./wait-for-it.sh", "mysql:3306", "--", "nodemon", "/bin/www"]